# ğŸ“º é¢‘é“åç§°
channel: "EchoroukTVOfficiel"

# ğŸ¯ è§†é¢‘æŠ“å–èŒƒå›´ï¼ˆä» start_index å¼€å§‹ï¼Œå·¦é—­å³å¼€ï¼‰
start_index: 11
end_index: 13

# ğŸ—£ï¸ å­—å¹•æ£€æµ‹ç›®æ ‡è¯­è¨€ï¼ˆåªæ£€æµ‹è¯¥è¯­è¨€ï¼‰
subtitle_lang: "en"

# âš™ï¸ æ‰€æœ‰è¿‡æ»¤æ¡ä»¶å½’åœ¨ filter ä¸‹
filter:
  # ğŸŒ è¯­è¨€è¿‡æ»¤å¼€å…³åŠç›®æ ‡åŒ¹é…è¯
  enable_language_filter: true
  target_language_abbr:
    - "algeria"
    - "ar"
    - "dz"
    - "algerie"
    - "alg"


  # ğŸ¬ æ—¶é•¿è¿‡æ»¤
  enable_duration_filter: true
  min_duration: 20       # å•ä½ï¼šç§’
  max_duration: 18000    # å•ä½ï¼šç§’

  # ğŸ‘ ç‚¹èµæ•°è¿‡æ»¤
  enable_like_count_filter: true
  min_like_count: 10

  # ğŸ™ï¸ å­—å¹•è¿‡æ»¤
  filter_no_subtitle: true           # ä¸¢å¼ƒæ— å­—å¹•è§†é¢‘
  filter_no_manual_subtitle: false   # ä¸¢å¼ƒæ— äººå·¥å­—å¹•è§†é¢‘


# âœ‚ï¸ åˆ‡åˆ†é…ç½®
slice_sample_rate: 16000   # è¾“å‡ºé‡‡æ ·ç‡ Hz
slice_save_audio: false    # æ˜¯å¦ä¿å­˜åˆ‡ç‰‡éŸ³é¢‘ï¼ˆfalse = åªä¿å­˜ JSONï¼‰
